Import('env')

lib_files = [
	'utils.cpp',
	'point.cpp'
]

lib = env.Library('utils', lib_files)
installed_lib = env.Install("{libs_dir}".format(libs_dir=env['LIBS_DIR']), lib)
env.Alias('buildLibs', installed_lib)
