Import('env')

lib_files = [
    'outputImageSequence.cpp',
	'socketInterface.cpp',
	'bufferOutput.cpp',
	'recognizeGestures.cpp',
]

lib = env.Library('outputMethod', lib_files)
installed_lib = env.Install("{libs_dir}".format(libs_dir=env['LIBS_DIR']), lib)
env.Alias('buildLibs', installed_lib)

files = [
]

SConscript(files)
