Import('env')

libs = [
    'detector',
	'utils',
	'outputMethod',
    # openCV libraries',
	'opencv_imgcodecs',
    'opencv_core',
]

libs.extend(env['OPENCVBUILDER_ADDITIONAL_LIBRARIES'])
libs.extend(env['TEST_LIBS'])
libs.extend(env['STD_LIBS'])

libs_path = [
    env['LIBS_DIR'],
	env['THIRD_PARTY_LIBS_DIR']
]

files = [
	'testContours.cpp',
	'testUtils.cpp',
	'findContoursTestSuite.cpp',
	'growRegionsTestSuite.cpp',
]

target = env.Program(files, LIBS=libs, LIBPATH=libs_path)
installed_bin = env.Install("{bin_dir}".format(bin_dir=env['TEST_BIN_DIR']), target)
bin = env.Alias("testRegionGrowing", installed_bin)
bin = env.Alias("testDetectors", installed_bin)
bin = env.Alias("unittest", installed_bin)
