Import('env')

libs = [
	'outputMethod',
]
libs.extend(env['UNITTEST_LIBS'])
libs.extend(env['STD_LIBS'])

libs_path = [
    env['LIBS_DIR'],
	env['THIRD_PARTY_LIBS_DIR']
]

files = [
	'kodiTestSuite.cpp',
]

target = env.Program(target='kodiUnittest', source=files, LIBS=libs, LIBPATH=libs_path)
installed_bin = env.Install("{bin_dir}".format(bin_dir=env['TEST_BIN_DIR']), target)
bin = env.Alias("testKodi", installed_bin)
bin = env.Alias("testOutputMethod", installed_bin)
bin = env.Alias("unittest", installed_bin)
