Import('env')

lib_files = [
    'inputVideo.cpp',
    'inputImageSequence.cpp',
	'captureVideo.cpp'
]

lib = env.Library('inputMethod', lib_files)
installed_lib = env.Install("{libs_dir}".format(libs_dir=env['LIBS_DIR']), lib)
env.Alias('buildLibs', installed_lib)

folders = [
    'test/SConscript'
]

SConscript(folders)
