Import('env')

folders = [
    'regionGrowing/SConscript',
]

SConscript(folders)

lib_files = [
    'imageProcBase.cpp',
	'regionGrowing/findContours.cpp',
	'regionGrowing/growRegions.cpp'
]

lib = env.Library('imProc', lib_files)
installed_lib = env.Install("{libs_dir}".format(libs_dir=env['LIBS_DIR']), lib)
env.Alias('buildLibs', installed_lib)
