Import('env')

libs = [
    'matcher',
	'openSURF',
    # openCV libraries',
	'opencv_features2d',
    'opencv_highgui',
    'opencv_imgproc',
    'opencv_core',
	# opencv libraries
	'check',
	env['STD_LIBS']
]

libs_path = [
    env['LIBS_DIR'],
]

files = [
	'testMatchers.cpp',
	'testOpenSurfMatcher.cpp'
]

env_matchers = env.Clone()

# Add c++ 11 support for compiling the original openSurf matcher
env_matchers['CPPFLAGS'].append(['-std=c++11'])

target = env_matchers.Program(files, LIBS=libs, LIBPATH=libs_path)
installed_bin = env_matchers.Install("{bin_dir}".format(bin_dir=env['BIN_DIR']), target)
bin = env_matchers.Alias("testMatchers", installed_bin)
bin = env_matchers.Alias("unittest", installed_bin)
