Import('env')

lib_files = [
    'bfMatcher.cpp',
	'flannBasedMatcher.cpp',
]

lib = env.Library('matcher', lib_files)
installed_lib = env.Install("{libs_dir}".format(libs_dir=env['LIBS_DIR']), lib)
env.Alias('buildLibs', installed_lib)

files = [
	'test/SConscript'
]
SConscript(files)
