Import('env')

lib_files = [
    'bfMatcher.cpp'
]

lib = env.Library('bestEffortMatcher', lib_files)
installed_lib = env.Install("{libs_dir}".format(libs_dir=env['LIBS_DIR']), lib)
env.Alias('buildLibs', installed_lib)

lib_files = [
    'flannBasedMatcher.cpp'
]

lib = env.Library('flannBasedMatcher', lib_files)
installed_lib = env.Install("{libs_dir}".format(libs_dir=env['LIBS_DIR']), lib)
env.Alias('buildLibs', installed_lib)