Import('env')

lib_files = [
	'kodi.cpp',
]

lib = env.Library('backend', lib_files)
installed_lib = env.Install("{libs_dir}".format(libs_dir=env['LIBS_DIR']), lib)
env.Alias('buildLibs', installed_lib)

files = [
	'unittest/SConscript'
]

SConscript(files)
