Import('env')

folders = [
    'regionGrowing/SConscript',
]

SConscript(folders)

lib_files = [
	'averageContourDetector.cpp',
	'simpleBlobDetector.cpp',
	# Grow regions
	'regionGrowing/findContours.cpp',
	'regionGrowing/growRegions.cpp'

]

lib = env.Library('detector', lib_files)
installed_lib = env.Install("{libs_dir}".format(libs_dir=env['LIBS_DIR']), lib)
env.Alias('buildLibs', installed_lib)

