Import('env')

libs = [
]

libs_path = [
    env['LIBS_DIR']
]

target = env.Program('testLogging.cpp', LIBS=libs, LIBPATH=libs_path)
installed_bin = env.Install("{bin_dir}".format(bin_dir=env['BIN_DIR']), target)
bin = env.Alias("testLogging", installed_bin)
bin = env.Alias("unittest", installed_bin)
