Import('env')

libs = [
]
libs.extend(env['STD_LIBS'])

libs_path = [
    env['LIBS_DIR'],
	env['THIRD_PARTY_LIBS_DIR']
]

files = [
	'simdUtilsTestSuite.cpp',
]

target = env.Program(target='simdUtilsUnittest', source=files, LIBS=libs, LIBPATH=libs_path)
installed_bin = env.Install("{bin_dir}".format(bin_dir=env['TEST_BIN_DIR']), target)
bin = env.Alias("testSimdUtils", installed_bin)
bin = env.Alias("testUtils", installed_bin)
bin = env.Alias("unittest", installed_bin)
