Import('env')

lib_files = [
#    'sift.cpp',
#    'surf.cpp',
#	'orb.cpp',
#	'brisk.cpp',
#	'freak.cpp',
	'brief.cpp'
]

lib = env.Library('descriptor', lib_files)
installed_lib = env.Install("{libs_dir}".format(libs_dir=env['LIBS_DIR']), lib)
env.Alias('buildLibs', installed_lib)
