Import('env')

lib_files = [
    'sift.cpp'
]

lib = env.Library('sift', lib_files)
installed_lib = env.Install("{libs_dir}".format(libs_dir=env['LIBS_DIR']), lib)
env.Alias('buildLibs', installed_lib)

lib_files = [
    'surf.cpp'
]

lib = env.Library('surf', lib_files)
installed_lib = env.Install("{libs_dir}".format(libs_dir=env['LIBS_DIR']), lib)
env.Alias('buildLibs', installed_lib)