Import('env')

folders = [
    'application/SConscript',
	'cm/SConscript',
    'descriptor/SConscript',
    'displacement/SConscript',
    'draw/SConscript',
    'imProc/SConscript',
    'match/SConscript',
    'log/SConscript',
    'inputMethod/SConscript',
    'outputMethod/SConscript'
]

SConscript(folders)

libs = [
    # Modules
    'inputMethod',
    'findTheBall',
    'descriptor',
    'displacementBase',
    'draw',
    'imProc',
    'matcher',
	'utils',
	'outputMethod',

	# 3rd party
	'openSURF',
 
    # openCV libraries
    'opencv_features2d',
    'opencv_highgui',
    'opencv_photo',
    'opencv_flann',
    'opencv_nonfree',
    'opencv_imgproc',
    'opencv_core',
    
    # Std libraries
    env['STD_LIBS']
]

if env['USE_STATIC_LIBS'] == True:
    libs.append([
        'liblibjpeg',
        'zlib'
    ])

libs_path = [
    env['openCV_LIBS_DIRS'],
    env['LIBS_DIR']
]

target = env.Program('proofOfConcept.cpp', LIBS=libs, LIBPATH=libs_path)
installed_bin = env.Install("{bin_dir}".format(bin_dir=env['BIN_DIR']), target)
bin = env.Alias("demo", installed_bin)

target = env.Program('pipeline.cpp', LIBS=libs, LIBPATH=libs_path)
installed_bin = env.Install("{bin_dir}".format(bin_dir=env['BIN_DIR']), target)
bin = env.Alias("pipeline", installed_bin)
