Import('env')

folders = [
    'application/SConscript',
    'descriptor/SConscript',
    'displacement/SConscript',
    'draw/SConscript',
    'imProc/SConscript',
    'match/SConscript',
    'log/SConscript',
    'inputMethod/SConscript'
]

SConscript(folders)

libs = [
    # Modules
    'inputMethod',
    'findTheBall',
    'surf',
    'sift',
    'displacementBase',
    'draw',
    'imProc',
    'bestEffortMatcher',
    'flannBasedMatcher',
 
    # openCV libraries
    'opencv_features2d',
    'opencv_highgui',
    'opencv_photo',
    'opencv_flann',
    'opencv_nonfree',
    'opencv_imgproc',
    'opencv_core',
    
    # Std libraries
    env['STD_LIBS']
]

if env['USE_STATIC_LIBS'] == True:
    libs.append([
        'liblibjpeg',
        'zlib'
    ])

libs_path = [
    env['openCV_LIBS_DIRS'],
    env['LIBS_DIR']
]

target = env.Program('proofOfConcept.cpp', LIBS=libs, LIBPATH=libs_path)
bin = env.Alias("demo", target)
